Portuguese Translation iOS
Greenstand/treetracker-ios pull request #125
Opened 2022-10-10 14:04 UTC by SevioCorrea

## Overview of changes

## How was the change tested

## Screenshots (if applicable)

2022-10-22 13:53 UTC, viniciusyr commented on TreeTracker/Resources/pt-BR.lproj/Localizable.strings
> +"AddTree.PhotoButton.Title.TakePhoto" = "Torar foto";
The correct is "Tirar foto". Just a wrong typed

2022-10-22 13:54 UTC, viniciusyr commented on TreeTracker/Resources/pt-BR.lproj/Localizable.strings
> +"Home.InfoLabel.TreesPlantedLabel.Text" = "Árvoes plantadas";
Is missing a single letter R. Just a wrong typed

2022-10-22 13:59 UTC, viniciusyr commented on TreeTracker/Resources/pt-BR.lproj/Localizable.strings
> +"Profile.ChangeUserButton.Title" = "Mudar usuário";
"Trocar de usuário" sounds better and more native than "Mudar usuário"

2022-10-22 14:06 UTC, viniciusyr commented on TreeTracker/Resources/pt-BR.lproj/Localizable.strings
> +"SignUp.TextInput.FirstName.Placeholder" = "Primeiro nome";
Only "Nome" sounds better and more native than "Primeiro nome".

2022-10-22 14:07 UTC, viniciusyr commented on TreeTracker/Resources/pt-BR.lproj/Localizable.strings
> +"SignUp.TextInput.LastName.Placeholder" = "Último nome";
"Sobrenome" sounds better and more native than "Último nome".

2022-10-22 14:13 UTC, viniciusyr requested changes
I put a comment on five of the lines where they needed a change or where a single letter is missing. After the fix, the request looks perfect.

2022-10-22 14:34 UTC, SevioCorrea commented
> I put a comment on five of the lines where they needed a change or where a single letter is missing. After the fix, the request looks perfect.

Hi Vinicius. Thanks. I changed all the words you suggested.

2022-10-22 14:48 UTC, viniciusyr submitted a review, later dismissed
This translation is perfect! Good job, Sevio!

2022-11-09 19:36 UTC, AlexCornforth requested changes
Thanks for this @SevioCorrea 👍 

Translation look great but there are a bunch of unrelated files in here. Could you revert anything that isnt required for the new translations.

2022-11-09 19:36 UTC, AlexCornforth commented on TreeTracker.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings
> +<?xml version="1.0" encoding="UTF-8"?>
This looks unrelated to the change. I assume this is SwiftUI previews, as we're not using swiftUI i think we should revert this change

2023-08-17 15:32 UTC, AlexCornforth commented
Closing as this was done in a different PR

2023-08-17 15:32 UTC, closed without merging